### ISSUE TITLE
Issue with JSON

### ISSUE THREAD

**Issue by bjoerm** [maju116/WhyR_Hamburg#2]
Hey @maju116,
Thanks for your presentation yesterday. I also had some issues with reading the JSON file. The CSV sample worked for me for most parts of the script, but not for all. Could you upload the full data as zipped CSV?

Thank you! :-)

**Comment by maju116** [comment]
Hi @bjoerm 

It's done, You can also find RData files too.

**Comment by bjoerm** [comment]
Thank you very much!
